import type { Metadata } from 'next';
import ArticleLayout from '@/app/guides/_shared/ArticleLayout';

export const metadata: Metadata = {
  title: 'Terms of Use',
  description:
    'Terms of use for FinCalc Smart financial calculators, AI insights, and PDF reports.',
};

const LAST_UPDATED = 'June 2026';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-bold text-slate-900 mb-3">{title}</h2>
      <div className="text-sm text-slate-600 leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <ArticleLayout>
      <div className="mx-auto max-w-3xl px-4 py-14 space-y-10">

        <div>
          <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Use</h1>
          <p className="text-sm text-slate-400">Last updated: {LAST_UPDATED}</p>
        </div>

        <Section title="1. Acceptance of terms">
          <p>
            By accessing or using FinCalc Smart, you agree to these Terms of Use. If you do not
            agree, please do not use the site. We may update these terms from time to time; continued
            use of the site after changes are posted constitutes acceptance of the updated terms.
          </p>
        </Section>

        <Section title="2. Educational purpose only">
          <p>
            FinCalc Smart is an educational tool. All calculators, AI-assisted insights, financial
            guides, and PDF reports are provided for informational and illustrative purposes only.
            Nothing on this site constitutes financial, tax, legal, mortgage, or investment advice.
          </p>
          <p>
            The site is designed to help you understand financial concepts and explore scenarios.
            It is not a substitute for advice from a qualified professional who understands your
            complete financial situation.
          </p>
        </Section>

        <Section title="3. Not financial, tax, legal, mortgage, or investment advice">
          <p>
            Results produced by FinCalc Smart calculators are estimates based on the inputs you
            enter and standard financial formulas. They do not account for your full financial
            circumstances, tax situation, credit profile, investment objectives, or applicable
            regulations.
          </p>
          <p>
            Before making financial, tax, mortgage, legal, or investment decisions, you should
            consult a qualified professional — such as a financial advisor, mortgage broker,
            accountant, or lawyer. FinCalc Smart does not provide, and nothing on this site should
            be interpreted as, advice in any of these areas.
          </p>
        </Section>

        <Section title="4. Calculator estimates and assumptions">
          <p>
            Calculator results are based on the inputs you provide and a set of assumptions built
            into each tool. These assumptions are described in each calculator&apos;s methodology
            section. Results will differ if your actual situation differs from those assumptions.
          </p>
          <p>
            Examples include, but are not limited to: fixed interest rate assumptions, simplified
            tax bracket estimates, inflation adjustments not applied unless stated, and standard
            regulatory thresholds that may change over time.
          </p>
        </Section>

        <Section title="5. PDF reports">
          <p>
            PDF reports generated by FinCalc Smart are educational scenario summaries based on
            the inputs you enter. They are not official financial documents, statements, or
            assessments. Do not use PDF reports as the sole basis for financial decisions.
          </p>
        </Section>

        <Section title="6. User responsibility">
          <p>
            You are responsible for the accuracy of the inputs you enter into calculators and
            for how you interpret and act on the results. FinCalc Smart is not responsible for
            decisions you make based on calculator outputs.
          </p>
          <p>
            You agree to use FinCalc Smart for lawful purposes only and not to attempt to
            interfere with the operation of the site.
          </p>
        </Section>

        <Section title="7. No guarantee of accuracy or future results">
          <p>
            FinCalc Smart aims to provide accurate calculations based on well-established formulas,
            but we do not warrant that all outputs are error-free or that they reflect the most
            current regulatory requirements. Financial regulations, tax brackets, and program rules
            change over time.
          </p>
          <p>
            Past or projected financial scenarios are not guarantees of future results. Market
            conditions, interest rates, tax laws, and personal circumstances can change in ways
            that are not modeled by these tools.
          </p>
        </Section>

        <Section title="8. Third-party links">
          <p>
            FinCalc Smart may include links to external websites for reference purposes. We do
            not endorse, control, or take responsibility for the content, accuracy, or practices
            of any third-party site. Visiting external links is at your own risk.
          </p>
        </Section>

        <Section title="9. Limitation of liability">
          <p>
            To the fullest extent permitted by applicable law, FinCalc Smart and its operators
            are not liable for any direct, indirect, incidental, or consequential damages arising
            from your use of the site, reliance on calculator results, or inability to access the
            site.
          </p>
          <p>
            The site is provided &ldquo;as is&rdquo; without warranties of any kind, express or
            implied.
          </p>
        </Section>

        <Section title="10. Changes to the service">
          <p>
            FinCalc Smart may modify, suspend, or discontinue any part of the site at any time
            without notice. We may add, change, or remove calculators, features, or content as
            the product evolves.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            If you have questions about these terms, you can contact us at{' '}
            <a href="mailto:contact@fincalcsmart.com" className="text-brand-teal hover:underline">
              contact@fincalcsmart.com
            </a>.
          </p>
        </Section>

      </div>
    </ArticleLayout>
  );
}
