import {
  Home, ShieldCheck, ClipboardCheck, Building2, RefreshCw,
  Scale, Umbrella, Wallet, TrendingUp,
  Percent, BarChart3, Layers, Hash, GitCompare,
  Flame, PiggyBank, Banknote, Target, Landmark,
  User, Car, CreditCard,
  Receipt, Briefcase, FileText,
  type LucideIcon,
} from 'lucide-react';

export interface CalcEntry {
  label: string;
  href: string;
  description: string;
  category: string;
  region: 'ca' | 'us' | 'both';
  icon: LucideIcon;
  iconColor: string;
  iconBg: string;
  available: boolean;
  /** Hide from nav/mega-menu — page still exists for SEO & direct access */
  navHidden?: boolean;
  /** If set, nav/search routes to the matching country URL instead of `href` */
  regionRoutes?: { ca: string; us: string };
  /** Generic label shown in search results instead of the full country-specific title */
  searchLabel?: string;
}

export const CALC_INDEX: CalcEntry[] = [
  // ── Mortgage ─────────────────────────────────────────────────────────────────
  {
    label: 'Canadian Mortgage Calculator',
    href: '/canadian-mortgage-calculator',
    description: 'Monthly payments, CMHC insurance, semi-annual compounding, GDS/TDS ratios, and a full amortization schedule.',
    category: 'Mortgage',
    region: 'both',
    icon: Home,
    iconColor: '#1DB584',
    iconBg: 'rgba(29,181,132,0.12)',
    available: true,
    regionRoutes: { ca: '/canadian-mortgage-calculator', us: '/us-mortgage-calculator' },
    searchLabel: 'Mortgage Calculator',
  },
  {
    label: 'US Mortgage Calculator',
    href: '/us-mortgage-calculator',
    description: 'Monthly payments, PMI, 28/36 rule, conventional & FHA loan comparisons, and a full amortization schedule.',
    category: 'Mortgage',
    region: 'us',
    icon: Home,
    iconColor: '#1DB584',
    iconBg: 'rgba(29,181,132,0.12)',
    available: true,
    navHidden: true,  // merged into the "Mortgage" nav entry above; page still accessible directly
  },
  {
    label: 'Mortgage Qualifier Calculator',
    href: '/mortgage-qualifier-calculator',
    description: 'Find out exactly how much mortgage you qualify for in Canada (GDS/TDS + B-20 stress test) or the USA (28/36 rule).',
    category: 'Mortgage',
    region: 'both',
    icon: ClipboardCheck,
    iconColor: '#1DB584',
    iconBg: 'rgba(29,181,132,0.12)',
    available: true,
  },
  {
    label: 'CMHC Insurance Calculator',
    href: '/cmhc-mortgage-insurance-calculator',
    description: 'Calculate your CMHC mortgage insurance premium for Canadian home purchases below 20% down payment.',
    category: 'Mortgage',
    region: 'ca',
    icon: ShieldCheck,
    iconColor: '#1DB584',
    iconBg: 'rgba(29,181,132,0.12)',
    available: true,
  },
  {
    label: 'Rent vs. Buy Calculator',
    href: '/rent-vs-buy-calculator',
    description: 'Compare the true long-term cost of renting versus buying a home in your market.',
    category: 'Mortgage',
    region: 'both',
    icon: Scale,
    iconColor: '#1DB584',
    iconBg: 'rgba(29,181,132,0.12)',
    available: true,
  },
  {
    label: 'Mortgage Refinance Calculator',
    href: '/mortgage-refinance-calculator',
    description: 'Find out if refinancing your mortgage makes financial sense and how long until you break even.',
    category: 'Mortgage',
    region: 'both',
    icon: RefreshCw,
    iconColor: '#1DB584',
    iconBg: 'rgba(29,181,132,0.12)',
    available: true,
  },
  // ── Financial Planning ────────────────────────────────────────────────────────
  {
    label: 'Net Worth Calculator',
    href: '/net-worth-calculator',
    description: 'Calculate your total net worth, debt-to-asset ratio, and liquidity position across all assets and liabilities.',
    category: 'Financial Planning',
    region: 'both',
    icon: Scale,
    iconColor: '#F59E0B',
    iconBg: 'rgba(245,158,11,0.12)',
    available: true,
    searchLabel: 'Net Worth Calculator',
  },
  {
    label: 'Emergency Fund Calculator',
    href: '/emergency-fund-calculator',
    description: 'Calculate your emergency fund target, current coverage in months, and how long it takes to reach your goal.',
    category: 'Financial Planning',
    region: 'both',
    icon: Umbrella,
    iconColor: '#F59E0B',
    iconBg: 'rgba(245,158,11,0.12)',
    available: true,
    searchLabel: 'Emergency Fund Calculator',
  },
  {
    label: 'TFSA Calculator',
    href: '/tfsa-calculator',
    description: 'Estimate how your Tax-Free Savings Account contributions may grow tax-free and check your contribution room usage.',
    category: 'Financial Planning',
    region: 'ca',
    icon: PiggyBank,
    iconColor: '#F59E0B',
    iconBg: 'rgba(245,158,11,0.12)',
    available: true,
    searchLabel: 'TFSA Contribution Growth Calculator',
  },
  {
    label: 'RRSP Savings Calculator',
    href: '/rrsp-savings-calculator',
    description: 'Estimate RRSP growth, check your first-year deduction room, and see a simplified tax refund estimate.',
    category: 'Financial Planning',
    region: 'ca',
    icon: Landmark,
    iconColor: '#F59E0B',
    iconBg: 'rgba(245,158,11,0.12)',
    available: true,
    searchLabel: 'RRSP Contribution Room Tax Refund Growth Calculator',
  },
  // ── Investing ─────────────────────────────────────────────────────────────────
  {
    label: 'Compound Interest Calculator',
    href: '/compound-interest-calculator',
    description: 'See how your savings grow with the power of compounding over time.',
    category: 'Investing',
    region: 'both',
    icon: Percent,
    iconColor: '#0EA5E9',
    iconBg: 'rgba(14,165,233,0.12)',
    available: true,
    searchLabel: 'Compound Interest Calculator',
  },
  {
    label: 'ROI Calculator',
    href: '/roi-calculator',
    description: 'Calculate return on investment, break-even point, and annualized ROI for any investment or project.',
    category: 'Investing',
    region: 'both',
    icon: BarChart3,
    iconColor: '#0EA5E9',
    iconBg: 'rgba(14,165,233,0.12)',
    available: true,
    searchLabel: 'ROI Calculator',
  },
  {
    label: 'Investment Fees Calculator',
    href: '/investment-fees-calculator',
    description: 'See how management fees and MERs compound over time to erode your returns.',
    category: 'Investing',
    region: 'both',
    icon: Layers,
    iconColor: '#0EA5E9',
    iconBg: 'rgba(14,165,233,0.12)',
    available: true,
    searchLabel: 'Investment Fees Calculator',
  },
  {
    label: 'Lump Sum vs Monthly Investment Calculator',
    href: '/lump-sum-vs-dca-calculator',
    description: 'Compare investing a lump sum immediately versus spreading the same amount as equal monthly contributions over time.',
    category: 'Investing',
    region: 'both',
    icon: GitCompare,
    iconColor: '#0EA5E9',
    iconBg: 'rgba(14,165,233,0.12)',
    available: true,
    searchLabel: 'Lump Sum vs DCA Calculator',
  },
  {
    label: 'Savings Goal Calculator',
    href: '/savings-goal-calculator',
    description: 'Estimate whether you are on track to reach a savings goal, how much you will have by your target date, and how much more you may need to save each month.',
    category: 'Financial Planning',
    region: 'both',
    icon: Target,
    iconColor: '#F59E0B',
    iconBg: 'rgba(245,158,11,0.12)',
    available: true,
  },
  // ── Retirement ────────────────────────────────────────────────────────────────
  {
    label: 'FIRE Calculator',
    href: '/fire-calculator',
    description: 'Estimate your FIRE number, projected timeline to financial independence, and FIRE age based on your portfolio, contributions, and expenses.',
    category: 'Retirement',
    region: 'both',
    icon: Flame,
    iconColor: '#F97316',
    iconBg: 'rgba(249,115,22,0.12)',
    available: true,
    searchLabel: 'FIRE Financial Independence Early Retirement Calculator',
  },
  {
    label: 'Retirement Savings Calculator',
    href: '/retirement-planning-calculator',
    description: 'Project your retirement savings growth, track progress toward your goal, and find the monthly contribution needed to close any gap.',
    category: 'Retirement',
    region: 'both',
    icon: Target,
    iconColor: '#F97316',
    iconBg: 'rgba(249,115,22,0.12)',
    available: true,
    searchLabel: 'Retirement Savings Calculator',
  },
  {
    label: 'Retirement Withdrawal Calculator',
    href: '/retirement-withdrawal-calculator',
    description: 'Estimate how long your retirement savings may last based on withdrawals, investment return, and inflation.',
    category: 'Retirement',
    region: 'both',
    icon: Banknote,
    iconColor: '#F97316',
    iconBg: 'rgba(249,115,22,0.12)',
    available: true,
  },
  // ── Loans ─────────────────────────────────────────────────────────────────────
  {
    label: 'Personal Loan Calculator',
    href: '/personal-loan-calculator',
    description: 'Calculate monthly payments, total interest, and true cost of borrowing for any personal loan.',
    category: 'Loans',
    region: 'both',
    icon: User,
    iconColor: '#3B82F6',
    iconBg: 'rgba(59,130,246,0.12)',
    available: true,
    searchLabel: 'Personal Loan Calculator',
  },
  {
    label: 'Car Loan Calculator',
    href: '/car-loan-calculator',
    description: 'Estimate your monthly car payment and total loan cost including interest.',
    category: 'Loans',
    region: 'both',
    icon: Car,
    iconColor: '#3B82F6',
    iconBg: 'rgba(59,130,246,0.12)',
    available: true,
    searchLabel: 'Car Loan Calculator',
  },
  {
    label: 'Debt Repayment Calculator',
    href: '/debt-repayment-calculator',
    description: 'See exactly when you\'ll be debt-free and how much interest you\'ll pay. Calculate how extra payments accelerate your payoff.',
    category: 'Loans',
    region: 'both',
    icon: CreditCard,
    iconColor: '#3B82F6',
    iconBg: 'rgba(59,130,246,0.12)',
    available: true,
  },
  // ── Tax & Salary ──────────────────────────────────────────────────────────────
  {
    label: 'Income Tax Calculator',
    href: '/income-tax-calculator',
    description: 'Estimate your federal and provincial/state income tax liability.',
    category: 'Tax & Salary',
    region: 'both',
    icon: FileText,
    iconColor: '#8B5CF6',
    iconBg: 'rgba(139,92,246,0.12)',
    available: true,
  },
  {
    label: 'Salary Calculator',
    href: '/salary-calculator',
    description: 'Convert your salary to hourly, weekly, monthly, or annual pay.',
    category: 'Tax & Salary',
    region: 'both',
    icon: Briefcase,
    iconColor: '#8B5CF6',
    iconBg: 'rgba(139,92,246,0.12)',
    available: true,
  },
  {
    label: 'Sales Tax Calculator',
    href: '/sales-tax-calculator',
    description: 'Calculate sales tax, HST, GST, or state sales tax on any purchase amount.',
    category: 'Tax & Salary',
    region: 'both',
    icon: Receipt,
    iconColor: '#8B5CF6',
    iconBg: 'rgba(139,92,246,0.12)',
    available: true,
  },
];

export function regionBadge(entry: CalcEntry): string {
  if (!entry.available) return 'Coming Soon';
  if (entry.region === 'ca') return 'Canada';
  if (entry.region === 'us') return 'USA';
  return 'CA & USA';
}
